### ISSUE TITLE
restiming causes redirect to beacon url

### ISSUE THREAD

**Issue by Cybermaxs** [lognormal/boomerang#74]
Hi,

I can't use the restiming plugin because there is a systematically redirect to the beacon handler when this plugin is added to the boomerang bundle.

Minimal repro (
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 101 Template</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <script src="boomerang.js"></script>
    <script src="restiming.js"></script>
    <script>
    BOOMR.init({
        beacon_url: "/boomerang_handler"
    });
</script>
  </head>
  <body>
    <h1>Hello, world!</h1>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </body>
</html>
```

![resttiming](https://cloud.githubusercontent.com/assets/4004029/12299201/eef6589c-ba15-11e5-9c92-d3c43b15949c.JPG)

From what I can see, there is because of the form.submit() on the child iframe created when the plugin is added to the page.

**Comment by bluesmoon** [comment]
Can you try pulling the code from https://github.com/lognormal/boomerang/pull/68 and see if that fixes it?  I remember we fixed this issue, but it hasn't been merged in because it's a large diff to code review.

**Comment by Cybermaxs** [comment]
I am aware of this PR and my repro was using files from the soasta-2015 branch. Sorry, It was not described

**Comment by bluesmoon** [comment]
@nicjansma can you have a look?

**Comment by KevinCammarata** [comment]
Is there any consideration being given to merging @Cybermaxs change into boomerang?  I am facing the same issue, and the suggested fix is working for us.

**Comment by nicjansma** [comment]
@KevinCammarata The changes in https://github.com/lognormal/boomerang/pull/68 were merged in, and should fix this issue.  See changes in `sendData` https://github.com/lognormal/boomerang/blob/master/boomerang.js#L680.

Please let me know if not.

**Comment by KevinCammarata** [comment]
The changes from #68 did not fix this issue for us.  We are using restiming with beacon_type set to post.  Even with the new changes, the form submit on line 741 is done on a document without a target.  By default, the target is set to "_self" which is causing the redirect.  

#75 addresses this problem nicely.

**Comment by bluesmoon** [comment]
@KevinCammarata I merged #75

**Comment by KevinCammarata** [comment]
Thanks!

**Comment by KevinCammarata** [comment]
Can you merge this to the Master branch?  I see it in the SOASTA branch.

**Comment by bluesmoon** [comment]
should be good now.
